DataCleaningScripts/check_reproductive_status.r
DataCleaningScripts/compare_tags.r
DataCleaningScripts/new_rodent_data.r

1) added script "check_reproductive_status.r"
2) changed new_rodent_data.r to: 
-call check_reproductive_status.r
-open the new data outside the quality control functions
3) changed compare_tags.r to accept a dataframe instead of an excel file to open

added quality control script to check reproductive status;

---

DataCleaningScripts/check_all_plots_present.r
DataCleaningScripts/check_stake_duplicates.r
DataCleaningScripts/new_rodent_data.r

for checking for duplicate stakes in rodent data and that all plots are present in the data

added scripts 

---

DataCleaningScripts/check_missing_data.r
DataCleaningScripts/new_rodent_data.r

added script to check for missing data that should apply to any type of data, check_missing_data.r
updated new_rodent_data.r

quality check: missing data

---

DataCleaningScripts/new_rodent_data.r

1) update new_rodent_data.r to check recaptures in new data against old data, and append new data to database
2) added period 447 to Portal_rodent.csv

update new_rodent_data.r and add period 447

---

DataCleaningScripts/.Rhistory

I didn't change anything in the cleaning script except the new period number...I think I just replaced it in my git folder and didn't push it up earlier.

Changed on record in 447 and appended 450 data

---

Ants/Portal_ant_species.csv

Replace fancy quotes in ant species file

---

DataCleaningScripts/new_met_data_to_db.R

new weather data

---

EML/eml_portal_data.R

I updated the contact info and added the cc by license. However, I couldn't actually get this code to write the file. Something I'm missing here?

Corrected contact info and license

---

DataCleaningScripts/new_rodent_data.r

added new data
changed sex of rodent from period 442

added period 455 rodent data

---

Plants/Portal_plant_census_dates.csv

Added dates of 2016 plant censuses
deleted some extra commas in 1998

add 2016 plant dates

---

DataCleaningScripts/new_moon_numbers.r

moved here from PortalDataSummaries repo

added script for adding new rows to moon_dates.csv

---

DataCleaningScripts/Create_portal_rodent_trapping_records.r

split into functions, one for creating the file from scratch and one for adding new rows
I don't know what's going on with all the commits.  I got confused about branches and forks.

improve create_portal_rodent_trapping.r

---

Plants/Portal_plant_species.csv

I must not have pulled recently enough and so I got some of Glenda's previous changes in here on accident. The ones I added are: hapl sp, micr sp, opun poly, euph sp, gili sp, and unkn shrb. Sorry for the confusion :/

adding new species from winter 2017 quadrats

---

.travis.yml
DataCleaningScripts/update_portal_plots.R
DataCleaningScripts/update_portal_rodent_trapping.r
install-packages.R

Automatically update the weather, trapping, plots, and new moon data using continuous integration.
Also cleans up a number of minor code issues that were preventing data cleaning scripts from
running on clean systems.

Continuous integration setup

---

Plants/Portal_plant_quadrats.csv

"quadrant" should be "quadrat"

changed plant quadrat column name typo

---

Plants/Portal_plant_species.csv

changed a couple things to make working with plant species easier

Portal_plant_species tweaking

---

.travis.yml
testthat/testthat.R

Fix testing so it fails on CI

---

.travis.yml
DataCleaningScripts/new_weather_data.R
Plants/Portal_plant_datanotes.txt
Plants/README.md
Rodents/Portal_rodent_datanotes.csv
Rodents/Portal_rodent_species.csv
Rodents/README.md
SiteandMethods/Methods.md
testthat.R
testthat/test-rodent_data.R
testthat/test-weather.R

Start fixing data that fail tests
Add body sizes to species list
Explain negative period codes in README

Add tests for rodent main data

---

DataCleaningScripts/clean_plant_quadrat_data.R
Plants/Portal_plant_census_dates.csv

updated "dates" in cleaning script also to format dates

add winter 2018 plant census data

---

Plants/Portal_plant_species.csv

Change lupi spar to lupi brev (correct code) in plant species and plant quadrat docs

Edit plant codes

---

DataCleaningScripts/new_moon_numbers.r
install-packages.R

The navy website is down. But there are packages that calculate lunar illumination. I chose the package lunar.

Switch to using lunar package to get new moon dates

---

.zenodo.json

Add some previous authors we tracked down

---

update_version.R

Use object['name-of-variable']

Non recursive vector is an atomic object

---

DataCleaningScripts/new_rodent_data.r

add 479 rodents

---

archive.R

Removes some unnecessary imports added during Travis debugging

Remove unnecessary imports [no version bump]

---

.travis.yml

Co-authored-by:Hao Ye <hao.ye@weecology.org>

remove depth limitation from git clone

---

DataCleaningScripts/clean_plant_quadrat_data.R
DataCleaningScripts/clean_shrub_transect_data.R
DataCleaningScripts/new_rodent_data.r

Changed user-specific paths to '~/Dropbox'. Closes #273. 
[no version bump]

Fix hardcoded Dropbox paths

---

archive.R

Check if the Travis build is initiated by a cron job:
* don't change the version #
* add "[cron"] to the commit message
closes #295

Travis cron patch

---

.gitignore
DataCleaningScripts/new_rodent_data.r

Rodents 482

---

archive.R

(not ready for merging yet)
Initial changes should fix #301 
See additional issue raised in [conversation from Jan 16](https://github.com/weecology/PortalData/pull/296#discussion_r259507797)

Improved case-handling in Archive.R

---

DataCleaningScripts/new_moon_numbers.r
DataCleaningScripts/new_rodent_data.r

Also had to update the new_moons function to add a period and census date to existing lines (if the new moon and new moon number have already been added, with period and census date as NA).

Add 488 rodent data [minor]

---

DataCleaningScripts/new_rodent_data.r
Rodents/Portal_rodent_species.csv

- add rodents 493
- add UB for "unidentified bird" to species list

Rodents 493 [minor]

---

DataCleaningScripts/clean_pit_tags.R
DataCleaningScripts/new_rodent_data.r

Co-Authored-By: Ellen Bledsoe <ellen.bledsoe@ufl.edu>
Co-Authored-By: Sarah Supp <sarah@weecology.org>
Co-Authored-By: Juniper Simonis <simonis@dapperstats.com>

Create unique ID column [major]

---

DataCleaningScripts/new_rodent_data.r

can I get you to review this for me, @gmyenni ?

[minor] adding rodents_499

---

DataCleaningScripts/new_rodent_data.r

can you review this for me @gmyenni ? Thanks!

add rodents_500[minor]

---

DataCleaningScripts/new_rodent_data.r

can you review this for me, @gmyenni ? thanks!

add rodents_501[minor]

---

DataCleaningScripts/new_rodent_data.r

all previous records of individual 793DA6 had hfl=25, wgt >= 25

add rodents_512[minor]

---

DataCleaningScripts/get_regional_weather.R
DataCleaningScripts/wu_loop.R
testthat/test-weather.R

* Combines all wunderground stations in one regional file
* Removes separate station files
* Breaking change in files/structure expected by [portalr](https://github.com/weecology/portalr/blob/main/R/Weather.R)
* Offline stations won't stop data updates (closes #428)

Add more wunderground stations [major]

---

DataCleaningScripts/new_rodent_data.r

plot 17 not censused because traps were not set night before (forgotten, sorry)

add rodent census 523 data [minor]
